[project]
name = "tarea-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = []

[dependency-groups]
dev = [
    "jedi-language-server>=0.43.1",
    "python-lsp-server>=1.12.2",
    "ruff>=0.9.9",
]

Cual es el objetivo de este archivo, no le encuentro logica, explicar por favor
